const LOAD_OPTIONS = {};

LOAD_OPTIONS.INIT = 'Home/LOAD_OPTIONS.INIT';
LOAD_OPTIONS.SUCCESS = 'Home/LOAD_OPTIONS.SUCCESS';
LOAD_OPTIONS.ERROR = 'Home/LOAD_OPTIONS.ERROR';

export default LOAD_OPTIONS;
